services:

  jangarong:
    restart: unless-stopped
    hostname: jangarong.internal
    image: jangarong/jangarong.github.io:4.0.0
    container_name: jangarong
    volumes:
      - ./volumes/assets:/app/public/assets/b/log
      - ./volumes/posts:/app/posts
    ports:
      - "3000:3000"
